// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://nvktxdmurllnfsvzmezn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52a3R4ZG11cmxsbmZzdnptZXpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMzQxMDMsImV4cCI6MjA3NzYxMDEwM30.e8WjT58618TIjMf-ibAmy_1_qugXTwaUiFefymDAGD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);